#!/usr/bin/env python3
"""
LinkedIn → Blog Pipeline
Converts a validated LinkedIn post into a blog article stub.

This script creates the blog post file with frontmatter.
The article CONTENT is generated by Charles (OpenClaw agent) directly —
no external API key needed.

Usage:
  python3 linkedin-to-blog.py --title "Title" --body article.md --tags "tag1,tag2"
  
The --body file should contain the full article markdown (generated by Charles).
"""

import os
import sys
import re
import json
import subprocess
from datetime import datetime
from pathlib import Path

SITE_DIR = Path(__file__).resolve().parent.parent
BLOG_DIR = SITE_DIR / "src" / "content" / "blog"


def slugify(text: str) -> str:
    """Generate URL-safe slug from title."""
    text = text.lower().strip()
    replacements = {
        'à': 'a', 'â': 'a', 'é': 'e', 'è': 'e', 'ê': 'e', 'ë': 'e',
        'î': 'i', 'ï': 'i', 'ô': 'o', 'ù': 'u', 'û': 'u', 'ü': 'u',
        'ç': 'c', 'œ': 'oe', 'æ': 'ae'
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    text = re.sub(r'[^a-z0-9\s-]', '', text)
    text = re.sub(r'[\s-]+', '-', text)
    return text.strip('-')[:80]


def create_blog_post(title: str, description: str, body: str,
                     tags: list[str], image: str = "",
                     linkedin_url: str = "") -> Path:
    """Write the markdown file for Astro Content Collections."""
    slug = slugify(title)
    filepath = BLOG_DIR / f"{slug}.md"

    today = datetime.now().strftime("%Y-%m-%d")
    tags_yaml = json.dumps(tags, ensure_ascii=False)

    frontmatter = f"""---
title: "{title}"
description: "{description}"
date: {today}
author: "Florent Coulon"
image: "{image}"
tags: {tags_yaml}
linkedin: "{linkedin_url}"
draft: false
---"""

    filepath.write_text(f"{frontmatter}\n\n{body}", encoding="utf-8")
    print(f"✅ Article: {filepath}")
    print(f"   Slug: {slug}")
    print(f"   Tags: {tags}")
    return filepath


def git_push(filepath: Path, title: str):
    """Git add, commit, push the new article."""
    repo_dir = SITE_DIR.parent
    subprocess.run(["git", "add", str(filepath)], cwd=repo_dir, check=True)
    subprocess.run(
        ["git", "commit", "-m", f"blog: {title}"],
        cwd=repo_dir, check=True
    )
    subprocess.run(
        ["git", "push", "origin", "main"],
        cwd=repo_dir, check=True, timeout=30
    )
    print("✅ Pushed → GitHub Actions → staging deploy")


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Create blog post from article body")
    parser.add_argument("--title", required=True)
    parser.add_argument("--body", required=True, help="Path to markdown file with article body")
    parser.add_argument("--description", default="")
    parser.add_argument("--tags", default="")
    parser.add_argument("--image", default="")
    parser.add_argument("--linkedin-url", default="")
    parser.add_argument("--no-push", action="store_true")
    args = parser.parse_args()

    body = Path(args.body).read_text(encoding="utf-8")
    tags = [t.strip() for t in args.tags.split(",") if t.strip()]
    description = args.description or (body[:157].rsplit(" ", 1)[0] + "..." if len(body) > 160 else body)

    filepath = create_blog_post(args.title, description, body, tags, args.image, args.linkedin_url)

    if not args.no_push:
        git_push(filepath, args.title)
    else:
        print("⏭️  --no-push: skipping git push")


if __name__ == "__main__":
    main()
